### ISSUE TITLE
BUG: !help command creates a character

### ISSUE THREAD

**Issue by GumTsun** [PositiveProgrammer/MMORPG-Discord-Bot#15]
Using the !help command displays the following:
MMORPG BOT V0.01
!create USERNAME GENDER
!chop USERNAME
!mine USERNAME
!display USERNAME

Along with listing the player commands it also uses the commands as it uses it, Meaning that it creates a bot with the username USERNAME and gender GENDER and then sends it mining and displays it.

**Comment by PositiveProgrammer** [comment]
Thanks, error has been fixed.
